const BlogPosts = [
    { 
        id: 1,
        title: 'Should Millenials Eschew Solo Home Ownership',
        content: `Millennials face a host of financial and life challenges that force them to delay “adulthood” compared to their parents and grandparents. One is that education inflation, and unpaid internships delay the start date for building wealth reminiscent of medieval apprentices. Student loans and inflation also eat up more of the money that millennials bring home with them such that even though they are saving more money than baby-boomers they may never be able to retire. Millenials are also concerned about global climate change to a larger extent than their forebears. All of these factors are delaying “normal” benchmarks for adulthood like marriage, having children, and buying a house, and I believe this will force them to become more creative in order to solve these problems and create generational wealth.

        This article, in particular, will focus on whether millennials should be homes in groups rather than trying to do so an individual or couple and there are several good reasons to do so. The first is that for many markets, the barrier to entry is too high for most Americans to afford property on one or two incomes. This means that people either need to leave their city to find a property that’s affordable and commit to a long commute or continue renting, in which case they are not building equity. By choosing a group of people to take out a mortgage together, you then have leverage to purchase homes in the locations that you want and even though you don’t own all of the shares in the house, you still are building equity. No longer will you be simply giving your money away to a landlord, who can evict you or sell the property; you can stay in your city and have more control over your life. If you get to the point where you decide that you want to own your home, then you can sell your shares of the first house.
        
        That control also includes distribution of risk and costs. A traditional mortgage is very risky if it relies on a single source of income to make all of the payments, during an economic downturn like the one due to Covid-19, many people lose their jobs and will be unable to make the payments even if they dip into saving, 401k’s, etc. Other home costs like upgrades, renovations, or repairs are also neglected because of high initial costs even if they will save homeowners money over the long run (e.g. solar panels). Another reason why homeowners won’t upgrade their properties is a perceived lack of time. Once you have a group of owners, then these problems start to go away; after a job loss your saving will stretch further because you only pay a fraction of the rent; if you want to install solar panels everyone only pays a small portion; some of the home owners may be more free to do work on a project in the morning, some at night or on weekends. Let’s do a little math on a house here in Seattle:
        
        My four friends and I are looking at a five bed, three bath, 2,633 square foot home that is listed for $749,950. The estimated monthly payment for the house is $3,501.
        If we put ten percent down, that’s $74,995, divided by five is $14,999.
        The monthly mortgage payment per person is $700, which is much less than the rent for a lot of places in Seattle.
        As you can see, our distributed costs make this investment much safer than if we were attempting it on our own.
        
        A third reason that individuals might want to band together is because it could reduce their carbon footprint by an average of 23%. Americans have built large homes but often don’t use the majority of their space regularly. If you have a large home but most of the space is unused, then all of the costs that go into heating/cooling the space is wasted but if you have more people living in the home then the total space is more likely to be used, and the individual carbon consumption is distributed among the homeowners. The savings in your carbon footprint also come from the fact that you can buy a home that will be in a neighborhood with a higher walkability index. You save money by not having to drive large distances for work or shopping. The last way that way that you can be greener by buying a home together is because the control of home ownership incentivizes you to upgrade the home and increase its value for later resale. If you were renting, you couldn’t make those decisions if you wanted to.
        
        The last big reason that I think co-ownership of a home is a smart move for millennials is because of its imitation of our hunter-gatherer ancestors. In Civilized to Death, Christopher Ryan argues that we should be looking for opportunities to mimic the social lives of hunter-gathers because it is the milieu that we have evolved with. Millennials report high levels of depression and isolation that may be the result of our industrial, atomized lifestyle. We did not evolve as individual animals like the big cats, but relied on close proximity to others for emotional support and cooperation for success. Co-owning a home with your friends gives you a built-in network similar to a tribe but on a much smaller scale; you may argue at times but the positives of the social arrangement should overcome the negatives. It gives you all an opportunity for democratic decision making in the house that might relieve tensions in a way that is better for every one. I have had friends tell me stories about how explosive arguments between partners occurred because interior became a battle of wills. Hopefully, by coming to consensus with multiple people about large decisions in a democratic way, it reinforces skills that transfer to your work or love life.
        
        To summarize, millennials have a rough time getting into the housing market and it puts them at a disadvantage when trying to build equity. I believe that purchasing a home with a group of friends is the safest and smartest choice for millennials as a whole to start taking control of their lives and building wealth and health. These reasons include the diffused costs and risks of home ownership, the reduction of individual carbon footprints, and the social benefits of co-habitation. Of course, there are people for whom this would not apply; individuals who may be moving from city to city very frequently, for example. But if the housing market in your area seems daunting, then this may be the solution for you.`,
        genre: '',
        publication_date: '09-17-2020'
    },
    {
        id: 2,
        title: 'Training For Wilderness Expedition',
        content: `This is a shortened version of a workshop that I gave at the Midwest Risk Management Symposium.

        Americans have been facing a demographic challenge due to the obesity epidemic that has serious implications for the outdoor recreation industry. According to the 2016 United States Report Card on Physical Activity, our youth are not meeting the minimum standards for physical activity; to summarize:
        
        Overall Activity Levels = D-
        Sedentary Behaviors = D-
        Active Transportation = F
        Organized Sport Participation = C-
        Health Related Fitness = D
        What this could mean for the industry is that the pool of potential participants is getting less healthy and fit before they arrive for programs like backpacking, and that the pool of people who might want to sign up in the first place is shrinking. The risk of injury to those who partake in wilderness programs goes up if they are less fit in the same way that it does for traditional sports. According to the national parks, the rates of injury have been going up linearly for the last decade and the number one cause of injury in the parks are to the ankle joint because of trips and falls.
        
        Due to the increased risk of soft tissue injury for participants at wilderness organizations like NOLS, Outward Bound or the YMCA, I seriously believe that they should start incorporating the research insights of kinesiologists and develop consistent standards for exercise before, during, and after expeditions. These standards and programs should increase the cardiovascular fitness, strength, and flexibility of participants which will reduce the risk of strains and sprains. An added benefit, would be that if an injury did occur that required an evacuation, having fitter participants to assist would relieve some of the stress and strain of the leaders.
        
        These fitness interventions can happen in three areas: pre-trip training using concurrent models, pre-habilitation on the trips, and resources to maintain fitness for when the trip is over. Concurrent training is when you combine strength and cardio in the same session on the same day. With concurrent training, there is a risk of an interference effect where either your strength or endurance gains are blunted because of inappropriately pairing your strength and cardio intensities. This can be avoided by following guidelines for developing peripheral (muscular) or central (nervous system) adaptations: peripheral strength with central endurance, or central strength with peripheral endurance. The order that you place the exercises will also have an effect on whether strength or endurance is most emphasized; by placing strength first it is emphasized and vice versa.
        
        On the trips I recommend a handful of easy-to-use guidelines: the first being mandatory warm-up and cool-down routines that are standardized. Warm-ups and cool-downs are known to increase flexibility, reduce injury incidences and soreness, and improve subsequent performance. Warm-ups should avoid static stretching and replace them with dynamic stretching, while cool-downs should incorporate static stretches that last at least 30 seconds and possibly myofascial release. Organizations can also add sport specific exercises to a daily routine that are meant to work smaller stabilizing muscles or the core; these are meant to reduce the likelihood of rotator cuff or hip impingement, low back pain, or other overuse injuries. They can be performed with body weight, resistance bands, or occlusion straps.
        
        Lastly, a lot of participants might want to take their new level of fitness and continue to improve upon it when they return home. I believe that organizations can easily provide resources for good nutrition and exercise that will point participants in the right direction. It also has benefits for the organization because it is part of the transfer that many professionals talk about. These participants learn and change on the trips, but how do they apply those lessons back home? I am a firm believer that the transfer of information regarding health and wellness should be a part of the curriculum for wilderness organizations. This can also incorporate information about food systems and their carbon/water footprint.
        
        In summation, as Americans become less fit the great outdoors become a more dangerous place. That danger can be reduced by incorporating insights from kinesiology in a standardized curriculum that can be done before, during, or after trips. These lessons have an immense carry over that can encourage future healthy habits and environmental stewardship. If there are individuals who would be interested in learn more of the specific steps that you can take, please refer to my youtube video posted above or reach out to me directly at mr.arthurdamato@gmail.com
        
        `,
        genre: '',
        publication_date: '09-13-2020'
    },
    {
        id: 3,
        title: 'The Power Of Closing Your Eyes',
        content: `Trainers and athletes are constantly on the lookout for new or better ways to improve the efficiency and efficacy of their programming, but not everything that one sees advertised is as good as the claims made about it. Battle ropes for instance have an overwhelming about of exposure in advertising and underwhelming results in the research literature, and if you want to learn more about the current state of research into battle ropes check out my previous blog post. More often than not people are looking for the newest gadget to get them the best results available, whether it’s devices or apps. They can be costly and ineffective despite the hype because the products appear on the markets before research does (with beaming models endorsing the product). I too look for tools and techniques, but as the manager of a boutique facility, I am limited in the amount of floor space where I can dump equipment.

        This is why I was delighted to come across research eyes-closed training (ECT). Requiring no additional purchasing or floor space, ECT is an excellent tool for professionals and laypeople, young and old, rich or poor. Take the same exercises that you might perform during a standard workout, close your eyes, and voila the exercise becomes more challenging even when the amount of sets, reps, and weight stay the same. The reason why it’s harder is because taking away visual information forces the brain to rely on another source of input: proprioception. The proprioceptive system is composed of receptors in muscles and tendons that allow one to know how quickly a muscle is moving (muscle spindles) and the forces acting on a muscle/tendon (Golgi tendon organ), and is trainable. Training this system improves balance and stability for the joint, which in turn can prevent injuries and improve performance. A good example is that patients with chronic ankle instability (CIA) require more visual input than healthy controls.
        
        Often balance training meant for proprioception is performed at the end of a session in a way that is joint specific: standing on BOSU balls or wobble boards, kneeling on Swiss balls, or running across balance pads, etc. However, time or resources may not permit extra time to be devoted to balance especially if strength or endurance are the primary goal of the program. By closing one’s eyes when performing standard strength exercises one stimulates the proprioceptive system at the same time that one works on strength and endurance. You can try it for yourself! Personally, I have felt comfortable performing up to my four rep max on exercises such as deadlifts, bench press and pistol squats, and felt the change in difficulty immediately. My senses were heightened throughout the full range of motion, and I could feel each muscle firing more acutely than when my eyes are open. It is particularly intense for my core. However, I know that my technique is not quite as good and would not recommend it for very heavy lifts similar to how Chan, 2018 recommends external focus cues for heavy lifts. 
        
        There are a few different strategies for incorporating ECT into your workouts. The first that I would recommend to novices is using ECT during warm-ups. Perform body-weight exercises and dynamic stretches because they are safe and the risk of injury from falling is slim. Examples include lunges, pushups, and pullups. As one feels more comfortable, a larger range of motion can be introduced to each of these moves (e.g. stepover lunges, crossover pushups, archer pullups). During the regular workout one might want to start ECT with pyramids or accessories; during the light reps of the pyramid keep the eyes closed, as the the sets get heavier feel free to open the eyes. Single joint accessories like bicep curls probably wouldn’t ever need one to open their eyes unless one absolutely needs to gaze upon oneself in the mirror. A third way to incorporate the ECT is to perform the first set with eyes closed merely to internally focus on the contractions of the muscles; for novices this may be a good way to teach them proper recruitment patterns. Subsequent sets then would have the eyes open to compensate for technique breakdowns associated with fatigue.
        
        These uses of ECT focus primarily on balance, stability, and technique, but more speculatively, ECT can be incorporated into hypertrophy protocols. It’s been shown that by internally focusing on the contraction of muscle during lifts, lifters can achieve greater hypertrophy. Closing one’s eyes and focusing entirely on the muscle should stimulate greater growth than opening them and being distracted by other stimuli in the gym. In this case, ECT is merely reinforcing a different stimuli that we know improves hypertrophy rather than by stimulating the proprioceptors for balance training. As a trainer, I constantly catch my clients looking at mirrors, clocks, and other people when they shouldn’t be. By requiring them to close their eyes, I am much more confident that they are doing what I ask. 
        
            To summarize, ECT brings the performer greater results by utilizing internal cues and improving balance. The advantages of utilizing ECT to traditional balance training is the efficiency of space and time. It should also teach one to internally faster. It is the cheapest tool on the market and everyone can benefit from it at some point. Don’t take my word for it, try it out yourself!`,
        genre: '',
        publication_date: '10-04-2019'
    },
    {
        id: 4,
        title: 'Outdoor Recreation Has An Exercise Problem',
        content: `I am not a man who is easily flustered, in fact, most people would compare me to a cucumber, and in leadership roles I have reacted with grace to challenge and bad attitude. However, a cluster of attitudes has consistently drawn my ire for almost ten years and still gives me grief. It is the consistent dismissal of exercise by peers in outdoor recreation in regards to how it can improve the experience and safety of participants. Every time that I extol the benefits of exercise to someone in outdoor recreation or experiential education there is push-back. Even worse is when someone pays lip service to exercise’s benefits regarding wellness or performance but refuses to implement even basic guidelines. I want to highlight a couple of examples that I have encountered and make it clear why the beliefs are at least wrongheaded and at worst dangerous.For ten years I have worked in outdoor recreation at a couple different organizations and given lectures on the benefits of specific exercise interventions for performance enhancement and risk management. As a strength and conditioning coach, I know that there are protocols to be implemented before, during, or after trips and expeditions at little or no cost, and with minimal time requirements. Clear exercise recommendations, the inclusion of activity specific warm-up and cool down routines, and guidance for maintaining fitness levels after an expedition would all add value to an organization’s tripping. Whether it’s a NOLS expedition, a college’s weekend climbing trip or a summer camping trip of one’s own, everyone can benefit from better physical preparedness during wilderness travel.

        One common remark said to me is that everyone already knows what to do (which couldn’t be further from the truth) and that staff are given the freedom to incorporate exercise as they please. This, I think, is just another application of the lauded Dunning-Kruger effect (individuals who know the least about a subject believe they know the most about it) wherein administrators and staff half remember their gym classes or sports coaches’ protocols from high school, or follow a fitness influencer on Instagram and believe they already know everything there is to exercise science. As a practitioner, it’s infuriating. Either a denial of progress in sports science or an appeal to authority is implied; nothing’s changed since Coach Steve taught baseball in ‘94 or an influencer’s body/aesthetics is resume enough to apply to every situation. The influencer is particularly infuriating because instagrammers don’t have to be able to even write quality programs for others to follow; four videos can be strung together in a single post with a few hashtags. 
        
        The fact is that there has been progress in exercise science and that credentials matter. Data driven protocols should be adopted and consistently enforced by management in outdoor recreation organizations whether it relates to the knots used to secure a top rope anchor or the warmups that reduce the likelihood of rotator cuff tears. The implementation of these protocols should be guided by individuals with extensive knowledge of biomechanics and physiology, and not by the employee who most recently played a sport or did a simple Google search. This manifestation of the Dunning-Kruger effect has given me many headaches, but at least education could be a remedy.
        
            The most dangerous poo pooing of exercise that I have heard was related to a trip leader (who was not alone) who wanted to experience the trip as similarly to their participants as they could. The reasoning was as follows: if I want to understand the emotions and stress of this trip on my participants then my body should be similar to theirs, my participants are unlikely to be very fit, therefore if I am unfit I will better be able to experience this trip through their perspective. This instructor was under the impression that they could better serve their participants because they would be able to empathize with them; if my body is tired, then so are the participants’ bodies. Assuming this belief is sincere — rather than a post hoc justification of bad behavior — it is inherently dangerous to both the instructor and the participants. 
        
            It purposefully introduces unnecessary risk onto an expedition that could be avoided, which is different from the other examples. The responsibility of participants’ safety is entirely on the instructor; it is why they have the education and equipment they do. Failing to bring important safety equipment could be considered negligence and I believe that purposefully atrophying one’s physical capabilities is also negligent for anyone associated with outdoor education or wilderness guiding. Whether it’s one’s strength, endurance or flexibility being reduced, could be all of the difference in a life or death scenario. Examples abound about how these attributes either saved or cost the life of a participant. As they diminish the likelihood that the instructor will become the victim in an accident also increases. 
        
            The first rescue that I had ever been a part of occurred when I was seventeen. A fellow participant had fallen down a steep ravine after the rocks he had been holding on to dislodged. The ordeal included a helicopter rescue that required myself, the instructor, two EMTs, and the other participant to put my compatriot on a toboggan and we hauled him up the ravine. At that time I was certainly the weakest link; could we have saved my friend if everyone else had my level of strength as a teenager? Maybe… But I am glad that that was not the case.
        
            Since that experience, I incorporated exercise into my pre-trip routines to ensure that I was always healthy before beginning my contracts. Looking back, however, my first attempts at program design were not appropriate for the stresses placed on my body and as I pursued my education in kinesiology my programming improved too. Even now, the type of training I would recommend for my younger self is completely different from what I had done, and different again from discipline to discipline. A rock climber, backpacker, and kayaker have entirely different needs in the wilderness and I hope that soon administrators will consult with strength coaches to identify those needs and implement the protocols that best meet them.`,
        genre: '',
        publication_date: '08-19-2019'
    },
    {
        id: 5,
        title: 'Ditch Your Financial Analyst, Get A Trainer',
        content: `Most people would agree that retirement planning is wise; it provides one with a safety net in case of lean times, the freedom to quit working if one is diligent, and the opportunity to spend retirement doing enjoyable things. A parent’s savings may even leave their children and grandchildren better off than when they set out into the world. In this article, I hope to show how working with a strength and conditioning coach, exercise physiologist, or personal trainer may be more crucial to a well rounded retirement plan than a financial planner.

        I realize that it may sound crazy to think that a trainer can help you retire better than a financial analyst, so I want to start by investigating short and long term benefits to working with a trainer. In the short term, a well made exercise program boosts your immune system, makes you stronger and more flexible, and these benefits reduce the number of days that an employee takes off of work due to sickness. The number one reason why employees take off during the year is because of low back pain, for which no pill will solve the underlying causes but exercise can. If an employee worked one more day a year over the course of their forty year career, assuming they work eight hours and the hourly wage is $15, then they would retire with an additional $4,800. However, a single bout of low back pain can take someone out for eight days or more. Of course, illness doesn’t simply cost you money because of lost wages but it also costs money because of the short term costs of buying medications, such as NyQuil. Currently, a 12 oz bottle of NyQuil costs about $7.69 and if you never bought one over the course of 40 years rather than one bottle a year, then you would have saved $307.60. Personally, I haven’t bought a single over-the-counter medication in five years and have never called in sick to work since graduating college. When I use sick days, they are to extend my vacations which I believe is much better way to use them than lying in bed feeling awful.
        
        If you think about larger bills that are accumulated lifestyle diseases, then you see the most extreme savings are due to your personal trainer. Diabetes, metabolic syndrome, arthritis, dementia, certain cancers, osteoporosis, and heart disease have all been linked to sedentary lifestyles and a sedentary lifestyle is an independent risk factor according to the American College of Sports Medicine. The average cost of diabetes alone is $16,752 according to the American Diabetes Association and these chronic diseases can force early retirements and drain the retirement savings of whole families. It is a cruel irony to work a lifetime to provide oneself a safety net, just to watch it dissolve a long with your health. People often complain about the price of their trainers but how would it compare to that one year of diabetes costs? If you met with a trainer for three days a week and each session was $50, then it would take you 111 weeks to use that money; one session a week would take 335. With the help of your trainer, you may never experience any of these diseases.
        
        Think of these diseases, independent of the costs, and how they will affect you during your retirement years. People with these conditions are often home bound and in chronic pain, turning their golden years into gilded ones. Even if you have adequate savings, what are you going to do with your time? Potentially, you may spend decades in a retirement home in front of a screen instead of actualizing yourself like my grandmother was able to do. She was able to visit all seven continents after her retirement and is active into her 90’s. She has never missed her grandchildrens’ weddings and was able to dance at them. Unfortunately, she is an outlier and unless you take care of your body you won’t experience retirement like her.
        
        As you can see, personal trainers’ and strength coaches’ primary function is to reduce your costs to the tune of tens of thousands of dollars while slightly increasing your wealth. Financial analysts on the other hand claim that they can grow your wealth in actively managed accounts in order to beat the market and provide you with enough money to retire on. According to an article from the Balance, actively managed accounts often fail to beat passively managed index funds over the long run and they include more costs and fees. Many financial analysts are not fiduciaries, meaning that they don’t have to make decisions that are in your best interest but in theirs because of lucrative commissions. If an advisor doesn’t maximize your profits, makes decisions that aren’t in your best interest and can’t minimize your losses, then are they truly worth the cost?
        
        Overall, it’s a question of risk. Proponents of actively managed accounts can beat the markets, and amass a fortune for clients but it’s unlikely. The risk of getting ill with either short term or chronic diseases is very high and the likelihood of injury in a gym due to poor programming or technique is moderately high, but these risks are mitigated by exercising with a qualified strength coach or trainer. The safest strategy for a retirement plan is to reduce as much risk as possible and not gamble with your finances.Therefore, a good plan for retirement would be maximize your wealth through passive index funds and to maximize your savings by hiring a trainer or strength coach.`,
        genre: '',
        publication_date: '10-13-2018'
    },
    {
        id: 6,
        title: 'Why Can\'t I Sell Better Sex',
        content: `Everyone knows the adage: sex sells. Sex sells product lines like make up and apparel, and entertainment such as movies and television. The way sex or titillation is sold to consumers is often blatant: buying this product will make you fuckable. How many men have gone out to buy cars and gadgets in the hopes that an attractive woman will see it and like a crow be drawn to their shiny trinkets? How many men are proud of their tailored suits and leather shoes that, like hermit crabs, cover their crusty frame? Lastly, how many men pop a blue pill– whether they need it or not– just to become intimate with a partner? I am a strength coach and can sell men the thing they most want: more frequent and better sex. Yet it is eternally frustrating to me that it is beyond the pale to directly market better sex to my clients and that we have to address it obliquely.

        The science is very clear that exercise has very positive benefits for the sexual functioning of  men. It reduces the likelihood of erectile dysfunction, reduces the risk of having your penis buried by your fat (it’s real), increases your testosterone, makes orgasm more satisfying, and simply makes you perform better for your partner. Whether it is strength or endurance training, increasing flexibility, or sex specific exercises like Kegels; a man’s performance in the bedroom is intimately tied to his performance in the gym. Most people in a gym have no intention of becoming athletes, but maybe I could motivate people to get into my facility if I had a big sign out front that said, “Want to be a better lover? Cum on in!” It would also be helpful to me if prospective clients would simply tell me that the thing they care most about is their sexual function and that they want to improve it, then I can tailor their programs better.
        
        If I had to speculate, it is probably a combination of male bravado and science denial. Admitting to sexual problems is hard, and I wouldn’t fault anyone for having difficulty discussing it. Men are much more prone to exaggerating their level of success between the sheets, in a car, or behind the bushes; everyone’s penis is ten inches and they take an hour to orgasm, and all of their partners are satisfied 100% of the time. If a man finally decided to get help, why on Earth would they trust such sensitive information to some lunk at Gold’s Gym rather than a urologist? However, the range of tools available to a medical professional confined to a clinic are in many ways more limited than a trainer’s; many don’t know how to appropriately prescribe exercise as medicine like an exercise physiologist or strength coach and they may only be able to prescribe pills or surgery. The other problem with seeing a urologist exclusively is that they have much more limited time to see their patient whereas the trainer can see their client practically as much as they want. The bonus being that you are awful at interpersonal communication you can practice with your trainer.
        
        That trainer should be capable of describing the science to their client. Many people are in denial of the benefits that can accrue to them through exercise. How will changing your body composition affect arterial stiffness, including the arteries of the penis? How will increasing your aerobic capacity improve the strength of an erection and improve stamina? How can specific core exercises prevent premature ejaculation? Will performing Zercher squats open up the possibility of new positions? I believe that many men want to believe that their penises or somehow independent of the rest of their body, like some sort of soul. They can abuse and neglect their body but that dick is going to work, damn it! A correlating idea is that once their penis is underperforming, it’s an inevitable result of age. Certainly, age is a predictor of declining sexual function. But that doesn’t explain sexual dysfunction for men in their 20’s through their 50’s. The younger that you develop a problem, the more likely that it’s a result of behavior and that it can be reversed.
        
        Maybe a man’s gadgets will get a woman into bed with him, but it does not guarantee a good performance. For that to happen, one needs a program that will turn one into a sexual athlete. I write excellent programs and want you to know it! If I could put that sign on my front lawn, I would definitely do so! If clients would approach me and be direct about their goals, I could help them. However, unless attitudes change toward marketing better sex, I can’t.`,
        genre: '',
        publication_date: '09-17-2018'
    },
    {
        id: 7,
        title: 'Book Review: The Secret Life of Fat by Sylvia Tara, PhD',
        content: `I picked up the Secret Life of Fat from Boswell Books in Milwaukee, and engrossed myself in Dr Tara’s popular science book for the rest of the day. Her narrative voice is an inviting and economical review of the scientific research on fat interwoven with personal stories from researchers and dieters who grappled with the problems of obesity. After only a few days, I had sped through a little more than 200 pages to finish the book, and wished that there was more to read!

        Dr Tara broke the book into three sections: one about how fat behaves as an endocrine organ, another about variety of ways fat interacts with the environment and is unique from one demographic to another, and lastly about the science of weight loss and management. The first two sections are an incredible example of how to take dry, scientific findings and make them engaging to a lay audience. Many will be shocked to learn how diverse and dynamic fat is, as opposed to being just that flab in the mirror that we wish would go away. For me, the case studies about rare diseases involving malfunctioning fat cells were particularly fascinating.
        
        As interesting as the first two sections are, the third is worth the asking price of the book by itself. Dr Tara cooly guides the reader through verified protocols for weight loss while acknowledging the challenges that genetics play for some. There are no gimmicks or scams. Dr Tara teaches one how to implement many weight loss protocols (e.g. intermittent fasting) and directs one to reliable resources for the protocols that she is not qualified to teach (e.g. Mindfulness). She also address the extra challenges placed on some by their unique biology and how to address it. I found it refreshing to read excellent advice that is amply cited, because every day I read about fitness gurus who sell snake oil. My one gripe with Dr Tara is her use of the term “weight loss” as opposed to “body composition.” If you lose 10lbs, it is not obvious that all or even most of that weight is fat. In fact, depending on the type of exercise regimen you follow that weight could be entirely fat or mostly lean muscle mass. Alternatively, after a successful intervention your weight may not change but you see drastic changes in body composition.
        
        Aside from that one contention, I thoroughly enjoyed Dr Tara’s book. It is concise, engaging, and people with a host of wonderful characters. She masterfully helps you empathize with these dieters and scientists as you learn more about the subject matter. By depicting their struggles, she teaches you the skills that they learned to make themselves happier and healthier. If you read this book, you will gain a whole new perspective about your body and be empowered with the tools to take charge of it.`,
        genre: '',
        publication_date: '08-11-2019'
    },
    {
        id: 8,
        title: 'Strength Training For A Backpacker',
        content: `Backpacking is a rewarding and challenging past time for millions of people. Loading up a pack and taking to the hills and mountains challenges the body in numerous ways. One hikes long distances on unstable terrain with the spine and hips loaded. In national parks hikers and backpackers routinely injure themselves by tripping and falling, which results in strains and sprains to the ankle, knee, and hip joint. Contusions are also a result of these falls. Many of these injuries are prevented by properly constructed exercise regimens but few people take the time to put together an appropriate program of their own. Many people do not prepare at all and others prepare inappropriately by selecting exercises that have little transfer to wilderness contexts. In this article, I will be taking you through a sample progression that I might use with my clients and explain why the progression is appropriate to the ‘sport’ of backpacking.

        This particular progression is for a novice lifter, where we will move from less technical two-legged exercises to technical, one-legged exercises. The reason why I want to move from two-legged to one-legged exercises is because the latter have a better transfer to wilderness contexts. The stability required by the hip, knee and ankle is not directly improved by exercises performed with two legs simultaneously, but they do provide loads to the spine and can increase the strength of the prime movers of those joints (quadriceps, hamstrings, and glutes) which is a good first step.
        
        If possible, I would have my clients begin their progression with both a back squat and kettlebell swing. The back squat directly loads the spine in a similar fashion to a backpack, unlike deadlifts or front squats which shift the center of mass further forward thereby decreasing the similarity between the exercise and backpacking. The load of the bar could be anywhere from 10-20% higher than the projected load of their pack. The kettlebell (or dumbbell) swing is an excellent companion to the back squat because it has a much higher horizontal component to the lift than other two-footed lifts. I would initially want my client to do more sets with less reps and a short rest period before progressing to higher repetitions. Maybe the goal is to do three sets of thirty repetitions (90 total reps); in the first weeks of the program they will do six sets of 15. This allows them to build their endurance without necessarily changing the total volume.
        
        The goal of the progression is to continue working those vertical and horizontal components while progressively moving to larger ranges of motion or reducing the limbs worked from two to one. Decreasing stability via one legged exercises shifts the emphasis away from the prime movers of the joint to other muscles that stabilize it. It also teaches the brain better proprioception and kinesthesia so that they react more quickly to loose or unstable terrain. The squat becomes an asymmetrically loaded back squat, where slightly more weight is placed on one side of the bar than the other, no more than five percent. Then it becomes a split squat and lastly a box step-up. What I do not recommend loading the spine of the athlete and then making them exercise on bosu or physioballs. Backpackers also should not perform ballistic exercises like jump squats or box jumps. These exercises either have too much risk for injury or too little transfer to the mountains and trails.
        
        The progression for the horizontal components would be as follows: kettlebell swing becomes barbell lunges, becomes stepover lunges, becomes stepover lunges where the planted foot is elevated. With each new exercise, there is more and more horizontal deviation for the hip joint. Even without changing dumbbell placement or the surface that the athlete steps on, the increased distance makes the exercise less stable and more challenging.
        
        Of course, this is not a complete program for backpackers, just the two most important lifts in the program. For a full program with accessories, prehabilitation, that also addresses additional goals of a client, I would need more time and testing. If you are interested in a  6-24 week program to prepare you for your wilderness excursions, feel free to shoot me an email. I could get you an online program through Google Drive in as little as week that includes nutritional information.`,
        genre: '',
        publication_date: '05-24-2018'
    },
    {
        id: 9,
        title: 'Canoecopia 2018',
        content: `For the past couple years I have been an attendant at the world’s largest paddle-sport expo, Canoecopia. As a Wisconsin resident, it’s been easy for me to take off for a day to peruse the newest gear, network, and listen to incredible lectures. I have wanted to do my own lecture since I first attended and this was finally the year that it happened!

        This past Saturday, I lectured on strength and conditioning applications for paddlesports to a packed room. If I had to guess, there were probably one hundred listeners who had come to hear the topic, which was a relief! I had worried that only my parents and friends would attend.
        
        My rapt audience sat through 35 minutes of dry science, metaphors, examples, and bad puns before engaging in a 10 minute Q and A. During that time I explained energy requirements of paddlesport disciplines, injury risks, and some fundamentals for program design. We even went through an example of how to write a 12-week periodized, concurrent strength program. Breaking it down my macro-, meso-, and micro cycles. It was a lot of information to cover, but I believe most listeners comprehended and retained the information.
        
        At the end of the discussion, I gave out all of the business cards that I had brought with me. Hopefully, these individuals will reach out and I can write them programs that fit their needs. Luckily, thanks to new apps I can write easy to use programs from a distance that include testing, tracking, video analysis, and progression.
        
        All in all, Canoecopia 2018 went better than I had hoped! Sweet gear, great people, professional validation; can it get any better?`,
        genre: '',
        publication_date: '03-13-2018'
    },
    {
        id: 10,
        title: 'The Next Step in Strength & Conditioning?',
        content: `I love strength and conditioning as a field, but wish that it had a broader base of support in regional communities. The dream for many professionals is to work with a collegiate or professional team in order to help them win championships. It’s easily the most lucrative position to be in, offers job security, and provides the coach with a captive audience who often want your advice to become a better performer. Unfortunately, working with teams is only going to get harder. The number of universities and professional teams aren’t growing quickly but the number of strength coaches is, which means that the odds of landing an incredible job in the upper echelons keeps diminishing. Some coaches are looking at sports that are new, like MMA, or finding sports that don’t traditionally utilize strength coaches, like rock climbing. Others are expanding into emergency services or high schools. Where else can strength coaches look to develop a new clientele?

        Maybe the answer is in outdoor recreation and expeditions. Every year, millions of people travel around the world looking for adventure in trips that can last months or years at a time in remote environs. These environs offer unique intellectual challenges for strength coaches, that can be radically different from classical sports. Imagine being the coach for a cadre of people who want to hike the entire Appalachian Trail: what kind of loads will they carry; what kind of injuries will they be predisposed to; how can you maximize the mileage they can cover every day; can you teach them techniques to reduce the likelihood of injury; and what kind of nutrition will they bring with them? Just for backpacking trips, the variables are fun to think about.
        
        But in the same way that emergency personnel have diverse needs, there are guiding and educational organizations that run diverse programs. NOLS, Outward Bound, and many others run trips that are up to several months long in individual or mixed disciplines. How would you write a program to reduce injury for rock climbing, canoeing, or horseback riding expeditions? Or if one trip flitted between all of them? I am sure that these organizations would love to know how they can reduce risk from the standpoint of their participants. From my own experience working at summer camps and at a collegiate outdoor program, I know that we spend a lot of time as staff to reduce the risk of injury by learning about equipment and trying to institute best practices, but we cannot control who walks through the door to participate in our programs. Imagine that were the case in football, the coaches spend weeks putting together game plans but there is no practice and unknown athletes simply show up on game day. It would be a nightmare. I believe that outdoor programs need to adopt some practices from professional sports.
        
        Maybe if strength coaches can help prepare participants before their trips, the rate of injuries will decrease. According to a 2008 study by the CDC, fractures (27.4%) and strains/sprains (23.9%) account for the largest number of hospitalizations for outdoor recreation. The same article concludes that one of the best ways to reduce injury would be to increase the fitness of participants, but it did not offer suggestions about what protocols to implement. Obviously, strength coaches could design programs that improve strength and balance, that in turn prevent fractures, sprains, and strains. These programs can be done with no equipment and remotely, thanks to the internet.
        
        There are also best practices for injury prevention during the expeditions, both acute and chronic. Good coaches dictate proper warm-up, cool-down, and recovery protocols that can be transferred to an expeditionary environment. Coaches could also prescribe prehabilitative exercises to the expedition. It’s a win for everyone. Coaches want clients, the companies want lower insurance and evacuation costs, and participants want to enjoy their trips to the utmost.
        
        Consider the impact a strength coach could have on the lives of the participants. The pool of people that are signing up to go on expeditions is getting less fit every year, it’s a general trend around the world, but I believe their preparedness could be much higher. These people want to have a life changing experience, not to get hurt, and to come home better than when they left. This is a motivated population who may not know the best way to prepare for their trip, but could follow a tailored, periodized program. From experience, I know that many of these people are disinterested in traditional sports, so having a positive experience with fitness would be more dramatic for them than a typical athlete. Maybe it would even transfer to their home-life once the trip is complete.
        
        I can think of no better justification for our industry than to show someone who has a very negative attitude towards fitness how proper coaching will change their life for the better. What’s more, by expanding into outdoor recreation strength and conditioning coaches could potentially reach tens of thousands of people who don’t currently see our value. Our new clients will be more resilient in the wilderness, companies can reap a higher profit margin by reducing their rate of injury, and we can find both personal and professional reward. This is why I think that we, as fitness professionals, should actively seek out partnerships between ourselves and outdoor recreation companies.`,
        genre: '',
        publication_date: '12-27-2017'
    }
]

export default BlogPosts;